spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix

server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000