spring:
  application:
    name: microservice-gateway-zuul-reg-exp
# 默认端口号为8041
server:
  port: 8041
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
