spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing

server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
microservice-provide-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule