spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing

server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled:false
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900