spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix-propagation

server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000