server:
  port: 7902
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
// hystrix默认是关闭的
feign:
  hystrix:
    enabled: true